[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "gcc"]
aptPkgs = ["python3-dev"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "source /opt/venv/bin/activate && python main.py"
